### ISSUE TITLE
Error in CMake

### ISSUE THREAD

**Issue by publicENEMY** [zuck/opengl-examples#1] opened 2015-06-05 00:19 UTC
I tried building project files for opengl-examples for visual studio using cmake-gui. The source I used was cloned opengl-examples.

Cmake settings
Where is the source code: e:/Users/iJam/Source/Repos/opengl-examples
Where to build the binaries: e:/Users/iJam/Source/Repos/opengl-examples/build

After i press configure, i get error in dialog box
Error
Error in configuration process, project files may be invalid

![image](https://cloud.githubusercontent.com/assets/2562219/7997064/1dbd00f6-0b5a-11e5-8b75-3954c3fcc288.png)

I tried putting proper glew and glfw directory like below

![image](https://cloud.githubusercontent.com/assets/2562219/7997137/252363fc-0b5b-11e5-95cd-7d86b87383fc.png)

After press configure until no reds, heres what i get.

![image](https://cloud.githubusercontent.com/assets/2562219/7997148/5ee8b308-0b5b-11e5-8c0d-189b46bd0446.png)

It might be silly mistake on my end, but im kinda noob in this cmake thing.

What did i do wrong and how to fix it?

Thanks.

**Comment by publicENEMY** [comment] 2015-06-05 00:32
Apparently, i got it working by putting location to glew library file instead of library directory.

Unfortunately, i got another error

Cannot open png.lib

![image](https://cloud.githubusercontent.com/assets/2562219/7997309/5c56b3c2-0b5d-11e5-8264-e19d27e29bea.png)

Here are my cmake settings

![image](https://cloud.githubusercontent.com/assets/2562219/7997301/42c212b2-0b5d-11e5-9310-8147b47df57b.png)

**Comment by diego3** [comment] 2016-06-13 19:04
I have got same errors, so many pain to get it working :(

**Comment by zuck** [comment] 2017-03-14 00:34
@publicENEMY @diego3 Sorry for unforgivable late reply. Did you find a solution to this problem?

BTW, the problem should be related with custom CMake's `FindGLFW.cmake` file used by the project to find the lib on your system. Apparently, the Win version doesn't handle it so well...

**Comment by zuck** [comment] 2018-01-27 18:04
A fix has been merged with #2. Kudos to @YunHsiao.

Please feel free to reopen if the problem is still there.

**Closed as completed by zuck** 2018-01-27 18:04 UTC
